package com.cs.tmt.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-06T22:37:40.791+05:30
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "InfoDataService",
                  wsdlLocation = "file:/D:/Sample%20Projects/CTS/TradeManagement/tmt-webservices-topDown/src/main/resources/InfoDataService.wsdl",
                  targetNamespace = "http://ws.tmt.cs.com")
public class InfoDataService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.tmt.cs.com", "InfoDataService");
    public final static QName InfoDataPort = new QName("http://ws.tmt.cs.com", "InfoDataPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/Sample%20Projects/CTS/TradeManagement/tmt-webservices-topDown/src/main/resources/InfoDataService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(InfoDataService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/Sample%20Projects/CTS/TradeManagement/tmt-webservices-topDown/src/main/resources/InfoDataService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public InfoDataService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InfoDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InfoDataService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public InfoDataService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public InfoDataService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public InfoDataService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns InfoDataPortType
     */
    @WebEndpoint(name = "InfoDataPort")
    public InfoDataPortType getInfoDataPort() {
        return super.getPort(InfoDataPort, InfoDataPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfoDataPortType
     */
    @WebEndpoint(name = "InfoDataPort")
    public InfoDataPortType getInfoDataPort(WebServiceFeature... features) {
        return super.getPort(InfoDataPort, InfoDataPortType.class, features);
    }

}
