package com.cs.tmt.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-01-06T22:37:38.377+05:30
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://ws.tmt.cs.com", name = "InfoDataPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InfoDataPortType {

    @WebMethod
    @WebResult(name = "getInfoDataResponse", targetNamespace = "http://ws.tmt.cs.com", partName = "response")
    public GetInfoDataResponse getInfoData(
        @WebParam(partName = "parameters", name = "getInfoDataRequest", targetNamespace = "http://ws.tmt.cs.com")
        GetInfoDataRequest parameters
    );

    @WebMethod
    @WebResult(name = "getInfoDataDetailsResponse", targetNamespace = "http://ws.tmt.cs.com", partName = "response")
    public GetInfoDataDetailsResponse getInfoDetails(
        @WebParam(partName = "parameters", name = "getInfoDataDetailsRequest", targetNamespace = "http://ws.tmt.cs.com")
        GetInfoDataDetailsRequest parameters
    );
}
